# Generated by Django 3.0 on 2020-07-24 01:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminmanagement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post_tags',
            name='posts',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='article_tag', to='adminmanagement.posts'),
        ),
    ]
