# Generated by Django 3.0 on 2020-07-24 02:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminmanagement', '0002_auto_20200724_0939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post_tags',
            name='tag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mytags', to='adminmanagement.tags'),
        ),
        migrations.AlterUniqueTogether(
            name='post_tags',
            unique_together={('posts', 'tag')},
        ),
    ]
