# Generated by Django 3.0 on 2020-07-25 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminmanagement', '0008_posts_encode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='tags',
        ),
        migrations.AddField(
            model_name='posts',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, to='adminmanagement.post_tags'),
        ),
    ]
