# Generated by Django 3.0 on 2020-07-25 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminmanagement', '0009_auto_20200725_1818'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='post_tags',
            new_name='articletags',
        ),
    ]
