# Generated by Django 3.0 on 2020-07-25 12:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('adminmanagement', '0010_auto_20200725_2000'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='posts',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, related_name='toarticletag', to='adminmanagement.articletags'),
        ),
    ]
