# Generated by Django 3.0 on 2020-07-26 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminmanagement', '0011_auto_20200725_2016'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='timestamp',
        ),
    ]
