# Generated by Django 3.0 on 2020-08-15 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminmanagement', '0012_remove_comments_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
