# Generated by Django 3.0 on 2020-08-24 15:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('websitemngnt', '0002_commenter'),
        ('adminmanagement', '0013_posts_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='visitor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='websitemngnt.commenter'),
        ),
    ]
