# Generated by Django 3.0 on 2020-08-24 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminmanagement', '0014_comments_visitor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='message',
            field=models.TextField(),
        ),
    ]
