# Generated by Django 3.0 on 2020-08-25 05:29

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('adminmanagement', '0016_comments_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 25, 5, 29, 46, 446233, tzinfo=utc)),
        ),
    ]
