# Generated by Django 3.0 on 2020-08-25 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminmanagement', '0018_auto_20200825_1441'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comments',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='posts',
            options={'ordering': ['-id']},
        ),
    ]
