# Generated by Django 3.0 on 2020-08-30 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminmanagement', '0019_auto_20200825_1606'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='descrip',
            field=models.CharField(default=1, max_length=300),
            preserve_default=False,
        ),
    ]
