# Generated by Django 3.0 on 2020-09-07 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminmanagement', '0020_posts_descrip'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='first_name',
            new_name='contact',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='last_name',
        ),
        migrations.AddField(
            model_name='profile',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
