# Generated by Django 3.0 on 2020-09-08 23:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminmanagement', '0022_auto_20200907_2212'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='bio',
            new_name='location',
        ),
    ]
