# Generated by Django 3.0 on 2020-09-15 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminmanagement', '0023_auto_20200908_2305'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ['-id']},
        ),
    ]
