# Generated by Django 3.0 on 2020-10-06 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='services',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shortdescrip', models.CharField(blank=True, max_length=200, null=True)),
                ('longdescrip', models.CharField(max_length=300)),
                ('price', models.FloatField()),
                ('edate', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
