# Generated by Django 3.0 on 2020-10-06 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='tags',
            field=models.CharField(default='laboratory', max_length=100),
            preserve_default=False,
        ),
    ]
