# Generated by Django 3.0 on 2020-08-25 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('websitemngnt', '0002_commenter'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commenter',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='gallery',
            options={'ordering': ['-id']},
        ),
    ]
